#[derive(Copy, Clone)]
#[repr(C, packed)]
pub struct VbeModeInfo {
    pub mode_attributes: u16,
    pub window_a_attributes: u8,
    pub window_b_attributes: u8,
    pub granularity: u16,
    pub window_size: u16,
    pub segment_a: u16,
    pub segment_b: u16,
    pub window_function_ptr: u32,
    pub pitch: u16,
    pub width: u16,
    pub height: u16,
    pub w_char: u8,
    pub y_char: u8,
    pub planes: u8,
    pub bpp: u8,  // bits per pixel
    pub banks: u8,
    pub memory_model: u8,
    pub bank_size: u8,
    pub image_pages: u8,
    pub reserved0: u8,
    pub red_mask_size: u8,
    pub red_field_position: u8,
    pub green_mask_size: u8,
    pub green_field_position: u8,
    pub blue_mask_size: u8,
    pub blue_field_position: u8,
    pub reserved_mask_size: u8,
    pub reserved_field_position: u8,
    pub direct_color_attributes: u8,
    pub framebuffer: u32,
    pub offscreen_mem_offset: u32,
    pub offscreen_mem_size: u16,
    pub reserved1: [u8; 206],
}
