[unstable]
build-std = ["core", "alloc", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86-unknown-bare-metal.json"

[profile.debug]
opt-level = 0
rustflags = [
    "-Crelocation-model=static",
]

[profile.release]
opt-level = 2
strip = "debuginfo"
rustflags = [
    "-Crelocation-model=static",
    # "-Clink-arg=-nostartfiles",
    # "-Clink-arg=-no-pic",
    #"-Clink-arg=-no-pie",
]
