[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86-unknown-bare-metal.json"
rustflags = [
    "-Crelocation-model=static",
    "-Clink-arg=-nostartfiles",
    "-Clink-arg=-no-pic",
    "-Clink-arg=-no-pie",
]

[profile.release]
opt-level = 2
strip = "debuginfo"
